---
title: "Fig_S4"
author: "Tord Ranheim"
date: '2024-12-20'
output:
  html_document:
    keep_md: no
---


Code to reproduce supplementary data figure 4

NB! The figure has been manually compiled in pages


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```


```{r}
rm(list=ls())
```


Libraries
```{r}
library(dplyr)
library(vegan)
library(tidyr)
library(ggplot2)
library(ggpubr)
```



Data loading
```{r Load data}

#Load metadata
metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

```



```{r Load files}

#Ncyc
ncyc = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional redundancy/Niche overlap/Ncyc/Results/res_lno_ncyc.txt")


```


                                        SET PLOT DETAILS
#############################################################################################

```{r Set plotting details}


ncyc$Succession = ordered(ncyc$Succession, levels = c("Managed","Recent","Late","Forest"))

farg = c("#bd0026","#fd8d3c", "#fecc5c", "skyblue2")

```



                                    FIG S4
#############################################################################################

```{r Fig S4a}

p1 <- ncyc %>%
  ggplot(aes(x = Sucession_numeric, y = value))+
  geom_jitter(aes(color = as.factor(Sucession_numeric)), 
              position=position_jitter(0.05),alpha = 0.3)+
     geom_smooth(
        aes(x = Sucession_numeric, y = value),
        color = "black",
        method = "lm",
        formula = y ~ x + I(x^2),
        #data = b2,
           linewidth = 1.2, 
        linetype = 1, 
        fullrange = T,
        se = T
    ) +
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.3,1.2)+
      theme_classic()+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
  theme(legend.position = "none")+
     theme(text=element_text(size=20));p1

p1 = p1 + stat_summary(fun.y = mean,
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "pointrange",
               colour = "grey9");p1

#Regression statistics
summary(lm(value ~ Sucession_numeric + I(Sucession_numeric^2),data= ncyc))

```


```{r Fig S4b}

p1 <- ncyc %>%
  filter(Community == "Bacteria") %>%
  ggplot(aes(x= variable, y = value, fill = Succession))+
  geom_boxplot(outlier.shape = NA)+
  scale_fill_manual(values = farg)+
      labs(fill = "Land use", y = "Genetic overlap")+
      ylim(0,1.3)+
      theme_classic()+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
   theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
  theme(legend.position = "none")+
     theme(text=element_text(size=20));p1

```


   

