---
title: "ED Fig. 1"
author: "Tord Ranheim"
date: '2024-12-14'
output:
  html_document:
    keep_md: no
---


Code to reproduce the Extended Data Fig. 1

NB! The figure has been manually compiled in pages


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```


```{r}
rm(list=ls())
```


Libraries
```{r}
library(dplyr)
library(vegan)
library(tidyr)
library(ggplot2)
library(ggpubr)
```



Data loading

```{r Load vs results}

vs_ad = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Alpha diversity/Variable selection/Results/results_variable_selection.txt")

vs_bd = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Beta diversity/Variation partitioning/Results/results_variable_selection_pcoa.txt")

```


                                        SET PLOT DETAILS
#############################################################################################

```{r Set plot details}

#fix names
names(vs_ad) = c("IncMSE","p.value","IncNodePurity","IncNodePurity.pvalue",
                 "Variable","Method","Community")

names(vs_bd) = c("IncMSE","p.value","IncNodePurity","IncNodePurity.pvalue",
                 "Variable","Method","Community")

#Add factor for p-value cutoff
vs_ad$Sign = ifelse(vs_ad$p.value > 0.05, "not sign", "sign")
vs_bd$Sign = ifelse(vs_bd$p.value > 0.05, "not sign", "sign")

#Set manual colors for p-value cutoff
pval = c("grey60","red4")

```


                                    EXTENDED DATA FIG. 1
#############################################################################################

```{r ED Fig. 1a-d}

#AD fungi
p1 = vs_ad %>% 
  filter(Method == "Omitted") %>%
  filter(Community == "Fungi") %>%
ggplot(aes(x = reorder(Variable, IncMSE), IncMSE)) +
  geom_bar(stat = "identity", aes(fill = Sign)) +
  scale_fill_manual(values = pval)+
  facet_wrap(~Community) +
  coord_flip() +
  theme_bw()+
   guides(fill="none") + 
    labs(x = "Explanatory variable", y = "IncMSE (%)") 

#AD bacteria
p2 = vs_ad %>% 
  filter(Method == "Omitted") %>%
  filter(Community == "Bacteria") %>%
ggplot(aes(x = reorder(Variable, IncMSE), IncMSE)) +
  geom_bar(stat = "identity", aes(fill = Sign)) +
  scale_fill_manual(values = pval)+
  facet_wrap(~Community) +
  coord_flip() +
  theme_bw()+
   guides(fill="none") + 
    labs(x = "", y = "IncMSE (%)") 

#BD fungi
p3 = vs_bd %>% 
  filter(Method == "Omitted") %>%
  filter(Community == "Fungi") %>%
ggplot(aes(x = reorder(Variable, IncMSE), IncMSE)) +
  geom_bar(stat = "identity", aes(fill = Sign)) +
  scale_fill_manual(values = pval)+
  facet_wrap(~Community) +
  coord_flip() +
  theme_bw()+
    #theme(text=element_text(size=16)) +
   guides(fill="none") + 
    labs(x = "Explanatory variable", y = "IncMSE (%)") 


#BD bacteria
p4 = vs_bd %>% 
  filter(Method == "Omitted") %>%
  filter(Community == "Bacteria") %>%
ggplot(aes(x = reorder(Variable, IncMSE), IncMSE)) +
  geom_bar(stat = "identity", aes(fill = Sign)) +
  scale_fill_manual(values = pval)+
  facet_wrap(~Community) +
  coord_flip() +
  theme_bw()+
   # theme(text=element_text(size=16)) +
   guides(fill="none") + 
    labs(x = "", y = "IncMSE (%)") 


```


```{r ED Fig. 1}

#Combine to one figure
ggarrange(p1,p2,p3, p4,
          labels = c("\u03b1","\u03b1","\u03b2","\u03b2"),
          ncol = 2, nrow = 2)

```

