---
title: "ED Fig. 5"
author: "Tord Ranheim"
date: '2024-09-24'
output:
  html_document:
    keep_md: no
---


Code to reproduce the Extended Data Fig. 5

NB! The figure has been manually compiled in pages


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```


```{r}
rm(list=ls())
```


Libraries
```{r}
library(dplyr)
library(vegan)
library(tidyr)
library(ggplot2)
library(ggpubr)
```



```{r Load metadata file}

metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

```

```{r Load Q R D results}

qrd = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional redundancy/Framework/Results/res_qrd.txt")

```

```{r merge}

master = left_join(qrd, metadata)
res = master %>% dplyr::select(Sample, Succession, Element, Q, R, D, pH, LDMC, C.N, Ecosystem_type, Tot_C)

rm(qrd, master)
```

                                        SET PLOT DETAILS
#############################################################################################

```{r Plot details}

#Set order of plotting
res$Succession = ordered(res$Succession, levels = c("Managed","Recent","Late","Forest"))

#Set manual color and shape
farg = c("#bd0026","#fd8d3c","#fecc5c", "skyblue2")
shape = c(21,23,24,25)
  
#Create median line for forest reference stage
f = res %>% filter(Succession == "Forest") 

```


                                    EXTENDED DATA FIG. 5
#############################################################################################

```{r Fig 5a}

h = median(subset(f, Element == "Carbon")$R, na.rm = T)

p1 = res %>%
  filter(Element == "Carbon") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = R, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
     ylim(0.48,0.67)+
      theme_classic()+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
     theme(text=element_text(size=20));p1

```


```{r Fig 5b}

h = median(subset(f, Element == "Carbon")$U, na.rm = T)

cu = res %>%
  filter(Element == "Carbon") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = U, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.35,0.55)+
      theme_classic()+
  #geom_line(aes(group = Par),alpha = 0.05)+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
  #theme(legend.position = "none")+
     theme(text=element_text(size=20));cu

```

```{r Extended data fig 5ab}

ggarrange(p1,p2,
          legend = "none")

```


```{r Fig 5c}

h = median(subset(f, Element == "Phosphorus")$R, na.rm = T)

p1 = res %>%
  filter(Element == "Phosphorus") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = R, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.4,0.71)+
      theme_classic()+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
     theme(text=element_text(size=20));p1

```


```{r Fig 5d}

h = median(subset(f, Element == "Phosphorus")$U, na.rm = T)

p2 = res %>%
  filter(Element == "Phosphorus") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = U, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.32,0.62)+
      theme_classic()+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
     theme(text=element_text(size=20));p2

```


```{r Fig. 5e}

h = median(subset(f, Element == "Nitrogen")$R, na.rm = T)

p1 = res %>%
  filter(Element == "Nitrogen") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = R, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.6,0.85)+
      theme_classic()+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
     theme(text=element_text(size=20));p1

```


```{r Fig. 5f}

h = median(subset(f, Element == "Nitrogen")$U, na.rm = T)

p2 = res %>%
  filter(Element == "Nitrogen") %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = U, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(0.2,0.42)+
      theme_classic()+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
     theme(text=element_text(size=20));p2

```


