---
title: "Beta_diversity_ver1"
author: "Tord Ranheim"
date: "2024-10-21"
output:
  html_document:
    keep_md: no
---


Beta diversity analyses


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```


```{r Load libraries}
library(tidyverse)
library(rmarkdown)
library(knitr)
library(magrittr)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(ggsci)
library(dplyr)
library(phyloseq)
library(microbiome)
library(vegan)
library(metagMisc)
library(MiscMetabar)
library(ape)
library(phylosmith)
library(microViz)
library(pairwiseAdonis)
```



```{r Clear directory and set seed}
rm(list=ls())
set.seed(123)
```


```{r Load srs-transformed phyloseq objects}

#Soil fungi
ps_fungi = readRDS("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Microbial/Amplicon/Soil/ITS/Processing/Results/ps_fungi_srs.RDS")

#Soil bacteria
ps_bacteria = readRDS("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Microbial/Amplicon/Soil/16S/Processing/Results/ps_bacteria_srs.RDS")

```


```{r Load metadata file}

metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

```


                                         PERMANOVA TESTS
###################################################################################################
```{r}
library("permute")
```

```{r Global permanova with unrestricted permutations}

ps_fungi %>% 
  adonis_pq("Succession", dist_method = "bray")

ps_bacteria %>% 
  adonis_pq("Succession", dist_method = "bray")


```


Now set up new tests with permutations restricted to pairs to account for matched study design

```{r Permanova with restricted permutations, fungi}
#First subset dataset to include only paired observations
m1 = metadata %>% filter(Sample %in% ps_fungi@sam_data$Sample) #make metadata file from phyloseq object

m1 = m1 %>% filter(n()>1, .by = Par) #Filter out all unmatched observations

h1 <- with(m1, how(blocks = Par, nperm = 9999)) #set permutation factor to paired sites

ps = ps_fungi %>% ps_filter(Sample %in% m1$Sample) #Filter phyloseq object to include only paired sites

dm = ps %>% phyloseq::distance(method = "bray")

#Global test for differences between all land-use stages
t1 =  adonis2(dm ~ sample_data(ps)$Succession,
                      permutations = h1,
                      method = "bray");t1


```



```{r Pairwise comparisons fungi}

#Pairwise comparisons of land-use stages using permanova
#As grassland sites are not matched, these will be evaluated separately 

ps_fungi_grass = ps_fungi %>% ps_filter(Succession != "Forest") #Subset ps to grassland sites only

groups <- as.data.frame(t(combn(unique(as.character(ps_fungi_grass@sam_data$Succession)), m = 2))) #Set contrasts

contrasts_g <- data.frame(
    group1 = groups$V1, group2 = groups$V2,
    R2 = NA, F_value = NA, df1 = NA, df2 = NA, p_value = NA
  ) #Create dataframe to add results to


#Loop through pairwise grassland comparisons and add results to data frame
for (i in seq(nrow(contrasts_g))) {
ps <- ps_fungi_grass %>% 
ps_filter(Succession %in% c(contrasts_g[i,1],contrasts_g[i,2]))#Subset phyloseq to contrasts

dm = ps %>% phyloseq::distance(method = "bray") #Calculate distance matrix

fit <- vegan::adonis2(dm ~ sample_data(ps)$Succession, 
                      nperm=9999,
                      method = "bray")

   contrasts_g$R2[i] <- round(fit$R2[1], digits = 3)
    contrasts_g$F_value[i] <- round(fit[["F"]][1], digits = 3)
    contrasts_g$df1[i] <- fit$Df[1]
    contrasts_g$df2[i] <- fit$Df[2]
    contrasts_g$p_value[i] <- fit$`Pr(>F)`[1]
}


#For pairwise comparisons between grassland and forest sites we create a separate loop that accounts for the paired structure of the dataset
groups <- as.data.frame(t(combn(unique(as.character(sample_data(ps_fungi)$Succession)), m = 2)))
groups <- groups[1:3,] #Restrict contrasts to grassland-forest comparisons

contrasts <- data.frame(
    group1 = groups$V1, group2 = groups$V2,
    R2 = NA, F_value = NA, df1 = NA, df2 = NA, p_value = NA
  )


#Loop over dataset to make pairwise permanova tests
for (i in seq(nrow(contrasts))) {

ps <- ps_fungi %>% 
ps_filter(Succession %in% c(contrasts[i,1],contrasts[i,2])) %>% #Subset phyloseq to contrasts
ps_filter(n()>1, .by = Par)  #Filter out unmatched observations

dm = ps %>% phyloseq::distance(method = "bray") #Calculate distance matrix

h <- with(sample_data(ps),how(blocks = Par, nperm = 9999)) #Restrict permutations

fit <- vegan::adonis2(dm ~ sample_data(ps)$Succession, 
                      permutation = h,
                      method = "bray")

   contrasts$R2[i] <- round(fit$R2[1], digits = 3)
    contrasts$F_value[i] <- round(fit[["F"]][1], digits = 3)
    contrasts$df1[i] <- fit$Df[1]
    contrasts$df2[i] <- fit$Df[2]
    contrasts$p_value[i] <- fit$`Pr(>F)`[1]
}


#Merge dataframes
res_fungi = rbind(contrasts,contrasts_g)

res_fungi$p_value_adjusted = p.adjust(res_fungi$p_value, method = "BH") #Adjust p-values for multiple comparisons

```


```{r Permanova restricted, bacteria}

##First subset dataset to include only paired observations
m1 = metadata %>% filter(Sample %in% ps_bacteria@sam_data$Sample) #make metadata file from phyloseq object

m1 = m1 %>% filter(n()>1, .by = Par) #Filter out all unmatched observations

h1 <- with(m1, how(blocks = Par, nperm = 9999)) #set permutation factor to paired sites

ps = ps_bacteria %>% ps_filter(Sample %in% m1$Sample) #Filter phyloseq object to include only paired sites

dm = ps %>% phyloseq::distance(method = "bray")

#Global test for differences between all land-use stages
t1 =  adonis2(dm ~ sample_data(ps)$Succession,
                      permutations = h1,
                      method = "bray");t1


```

```{r Pairwise comparisons bacteria}

#Pairwise comparisons of land-use stages using permanova
#As grassland sites are not matched, these will be evaluated separately 

ps_bac_grass = ps_bacteria %>% ps_filter(Succession != "Forest") #Subset ps to grassland sites only

groups <- as.data.frame(t(combn(unique(as.character(ps_bac_grass@sam_data$Succession)), m = 2))) #Set contrasts

contrasts_g <- data.frame(
    group1 = groups$V1, group2 = groups$V2,
    R2 = NA, F_value = NA, df1 = NA, df2 = NA, p_value = NA
  ) #Create dataframe to add results to


#Loop through pairwise grassland comparisons and add results to data frame
for (i in seq(nrow(contrasts_g))) {
ps <- ps_bac_grass %>% 
ps_filter(Succession %in% c(contrasts_g[i,1],contrasts_g[i,2]))#Subset phyloseq to contrasts

dm = ps %>% phyloseq::distance(method = "bray") #Calculate distance matrix

fit <- vegan::adonis2(dm ~ sample_data(ps)$Succession, 
                      nperm=9999,
                      method = "bray")

   contrasts_g$R2[i] <- round(fit$R2[1], digits = 3)
    contrasts_g$F_value[i] <- round(fit[["F"]][1], digits = 3)
    contrasts_g$df1[i] <- fit$Df[1]
    contrasts_g$df2[i] <- fit$Df[2]
    contrasts_g$p_value[i] <- fit$`Pr(>F)`[1]
}


#For pairwise comparisons between grassland and forest sites we create a separate loop that accounts for the paired structure of the dataset
groups <- as.data.frame(t(combn(unique(as.character(sample_data(ps_bacteria)$Succession)), m = 2)))
groups <- groups[1:3,] #Restrict contrasts to grassland-forest comparisons

contrasts <- data.frame(
    group1 = groups$V1, group2 = groups$V2,
    R2 = NA, F_value = NA, df1 = NA, df2 = NA, p_value = NA
  )


#Loop over dataset to make pairwise permanova tests
for (i in seq(nrow(contrasts))) {

ps <- ps_bacteria %>% 
ps_filter(Succession %in% c(contrasts[i,1],contrasts[i,2])) %>% #Subset phyloseq to contrasts
ps_filter(n()>1, .by = Par)  #Filter out unmatched observations

dm = ps %>% phyloseq::distance(method = "bray") #Calculate distance matrix

h <- with(sample_data(ps),how(blocks = Par, nperm = 9999)) #Restrict permutations

fit <- vegan::adonis2(dm ~ sample_data(ps)$Succession, 
                      permutation = h,
                      method = "bray")

   contrasts$R2[i] <- round(fit$R2[1], digits = 3)
    contrasts$F_value[i] <- round(fit[["F"]][1], digits = 3)
    contrasts$df1[i] <- fit$Df[1]
    contrasts$df2[i] <- fit$Df[2]
    contrasts$p_value[i] <- fit$`Pr(>F)`[1]
}


#Merge dataframes
res_bacteria = rbind(contrasts,contrasts_g)

res_bacteria$p_value_adjusted = p.adjust(res_bacteria$p_value, method = "BH") #Adjust p-values for multiple comparisons

```



                                        CALCULATE EFFECT SIZE
###########################################################################################

sourced from: https://stackoverflow.com/questions/74446879/how-can-the-effect-size-of-a-permanova-be-calculated

```{r Effect size function}

#' Calculate (partial) Omega-squared (effect-size calculation) for PERMANOVA and add it to the input object
#'
#' @param adonisOutput An adonis object
#' @param partial Should partial omega-squared be calculated (sample size adjusted). Default TRUE
#' @return Original adonis object with the (partial) Omega-squared values added
#' @import vegan
#' @export
adonis_OmegaSq <- function(adonisOutput, partial = TRUE){
    if(!(is(adonisOutput, "adonis") || is(adonisOutput, "anova.cca")))
        stop("Input should be an adonis object")
    if (is(adonisOutput, "anova.cca")) {
        aov_tab <- adonisOutput
        aov_tab$MeanSqs <- aov_tab$SumOfSqs / aov_tab$Df
        aov_tab$MeanSqs[length(aov_tab$Df)] <- NA
    } else {
        aov_tab <- adonisOutput$aov.tab
    }
    heading <- attr(aov_tab, "heading")
    MS_res <- aov_tab[pmatch("Residual", rownames(aov_tab)), "MeanSqs"]
    SS_tot <- aov_tab[rownames(aov_tab) == "Total", "SumsOfSqs"]
    N <- aov_tab[rownames(aov_tab) == "Total", "Df"] + 1
    if(partial){
        omega <- apply(aov_tab, 1, function(x) (x["Df"]*(x["MeanSqs"]-MS_res))/(x["Df"]*x["MeanSqs"]+(N-x["Df"])*MS_res))
        aov_tab$parOmegaSq <- c(omega[1:(length(omega)-2)], NA, NA)
    } else {
        omega <- apply(aov_tab, 1, function(x) (x["SumsOfSqs"]-x["Df"]*MS_res)/(SS_tot+MS_res))
        aov_tab$OmegaSq <- c(omega[1:(length(omega)-2)], NA, NA)
    }
    if (is(adonisOutput, "adonis"))
        cn_order <- c("Df", "SumsOfSqs", "MeanSqs", "F.Model", "R2",
                      if (partial) "parOmegaSq" else "OmegaSq", "Pr(>F)")
    else
        cn_order <- c("Df", "SumOfSqs", "F", if (partial) "parOmegaSq" else "OmegaSq",
                      "Pr(>F)")
    aov_tab <- aov_tab[, cn_order]
    attr(aov_tab, "names") <- cn_order
    attr(aov_tab, "heading") <- heading
    if (is(adonisOutput, "adonis"))
        adonisOutput$aov.tab <- aov_tab
    else
        adonisOutput <- aov_tab
    return(adonisOutput)
}

```

```{r Permanova by ecosystem}

dm = ps_bacteria %>% phyloseq::distance(method = "bray")
fit = vegan::adonis2(dm ~ sample_data(ps_bacteria)$Ecosystem, 
                      nperm=9999,
                      method = "bray")
r1 = adonis_OmegaSq(fit, partial = T)
r1$Community = "Bacteria"


dm = ps_fungi %>% phyloseq::distance(method = "bray")
fit = vegan::adonis2(dm ~ sample_data(ps_fungi)$Ecosystem, 
                      nperm=9999,
                      method = "bray")
r2 = adonis_OmegaSq(fit, partial = T)
r2$Community = "Fungi"

res_es = rbind(r1,r2)

write.table(res_es, file = "es_permanova.txt")

```



                                        DERIVE PCoA AXES
###########################################################################################

To calculate PCoA, use the base R function cmdscale (note that vegan contains the function wcmdscale, which in default setting is doing the same): 

```{r Derive PCoA axes}

#Fungi
dm = ps_fungi %>% phyloseq::distance("bray")
f1 = wcmdscale(dm, k = 2, eig = T)
f2 = data.frame(f1[["points"]])
names(f2) = c("PCoA1_fungi", "PCoA2_fungi")
f2$Sample = row.names(f2)


#Bacteria
dm = ps_bacteria %>% phyloseq::distance("bray")
f1 = wcmdscale(dm, k = 2, eig = T)
b2 = data.frame(f1[["points"]])
names(b2) = c("PCoA1_bacteria", "PCoA2_bacteria")
b2$Sample = row.names(b2)


#Add to metadata
m1 = metadata %>% dplyr::select(Sample)
m1 = left_join(m1, b2)
m1 = left_join(m1,f2)


#Write file
write.table(m1, file = "res_PCoA.txt")

rm(f1,f2,b2,dm)


```






