---
title: "variable_selection_ver1"
author: "Tord Ranheim"
date: "2024-11-08"
output:
  html_document:
    keep_md: no
---


Variable selection of functional diversity


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```



###loading requisite libraries 
```{r libraries to load}
library(tidyverse)
library(rmarkdown)
library(knitr)
library(magrittr)
library(rfPermute)
library(randomForest)
```


##Clear the directory and set pathway
```{r}
rm(list=ls())

```


Data loading
```{r Load data}

#Load metadata
metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

#Load nog diversity results
nog_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/NOG/Results/nog_diversity.txt")

#Load cazyme diversity results
cazyme_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Cazyme/Results/cazyme_diversity.txt")

#Load ncyc diversity results
ncyc_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Ncyc/Results/ncyc_diversity.txt")

#Load pcyc diversity results
pcyc_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Pcyc/Results/pcyc_diversity.txt")

```


```{r Load environmental variables}

env_omit = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Partitioning/Results/env_omit.txt")

env_imputed = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Partitioning/Results/env_imputed.txt")

```



                                      PREPARE DATASET
###################################################################################################

```{r prepare datasets}

#Merge functional diversity results
res = left_join(cazyme_results, ncyc_results)
res = left_join(res, pcyc_results)
res = left_join(res, nog_results)

#Dataset with omitted variables
df_omit = env_omit
df_omit$Sample = row.names(env_omit)
df_omit = left_join(df_omit, res)


rm(env_omit)
```


                                  
                                        RANDOM FOREST
###################################################################################################
file:///Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/rfPermute/rfPermute_Tutorial.html

```{r cazyme diversity fungi}

#With omitted values
t1 = df_omit[,c(1:11,13)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(cazyme_diversity_fungi ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Fungi"
r1$Function = "CAZyme"
r1$Variable = row.names(r1)

s1 = r1

```


```{r cazyme diversity bacteria}

#With omitted values
t1 = df_omit[,c(1:11,14)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(cazyme_diversity_bacteria ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Bacteria"
r1$Function = "CAZyme"
r1$Variable = row.names(r1)

s2 = r1

```


```{r pcyc diversity fungi}

#With omitted values
t1 = df_omit[,c(1:11,16)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(pcyc_diversity_fungi ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Fungi"
r1$Function = "Pcyc"
r1$Variable = row.names(r1)

s3 = r1

```

```{r pcyc diversity bacteria}

#With omitted values
t1 = df_omit[,c(1:11,17)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(pcyc_diversity_bacteria ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Bacteria"
r1$Function = "Pcyc"
r1$Variable = row.names(r1)

s4 = r1

```


```{r ncyc diversity bacteria}

#With omitted values
t1 = df_omit[,c(1:11,15)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(ncyc_diversity_bacteria ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Bacteria"
r1$Function = "Ncyc"
r1$Variable = row.names(r1)

s5 = r1

```

```{r nog diversity fungi}

#With omitted values
t1 = df_omit[,c(1:11,18)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(nog_diversity_fungi ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Fungi"
r1$Function = "NOG"
r1$Variable = row.names(r1)

s6 = r1

```



```{r nog diversity bacteria}

#With omitted values
t1 = df_omit[,c(1:11,19)] 
t1 = na.omit(t1)
  
rfp <- rfPermute(nog_diversity_bacteria ~ ., t1, ntree = 1000, num.rep = 1000, num.cores = 10)

plotImportance(rfp)
round(rfPermute::importance(rfp), 3)

#save results
r1 = data.frame(round(rfPermute::importance(rfp), 3))
r1$Community = "Bacteria"
r1$Function = "NOG"
r1$Variable = row.names(r1)

s7 = r1

```


```{r Merge and write results}

res = rbind(s1,s2,s3,s4,s5,s6,s7)

write.table(res, file = "results_variable_selection_fd.txt")

```

