---
title: "Fig. 2"
author: "Tord Ranheim"
date: '2024-10-28'
output:
  html_document:
    keep_md: no
---


Code to reproduce panels in manuscript figure 2

NB! The figure has been manually compiled in pages


```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```


```{r}
rm(list=ls())
```


Libraries
```{r}
library(dplyr)
library(vegan)
library(tidyr)
library(ggplot2)
library(ggpubr)
```


Data loading
```{r Load data}

#Load metadata
metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

```

```{r Load ad results}

#Load alpha diversity results
ad_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Alpha diversity/Results/alpha_diversity.txt")

```


```{r Load srs-transformed phyloseq objects}

#Soil fungi
ps_fungi = readRDS("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Microbial/Amplicon/Soil/ITS/Processing/Results/ps_fungi_srs.RDS")

#Soil bacteria
ps_bacteria = readRDS("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Microbial/Amplicon/Soil/16S/Processing/Results/ps_bacteria_srs.RDS")

```

```{r Load effect size results}

es_alpha = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Revision/diversity/results/es_ad.txt")

es_beta = read.table("//Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Revision/diversity/results/es_bd.txt")
  
```



                                         PREPARE DATASET
#############################################################################################

```{r prepare for alpha diversity plots}

metadata = left_join(metadata,ad_results)

```


                                        SET PLOT DETAILS
#############################################################################################

```{r Set plotting details}

#Set order of plotting
metadata$Succession = ordered(metadata$Succession, levels = c("Managed","Recent","Late","Forest"))
levels = c("Managed","Recent","Late","Forest")


#Set manual color and shape
farg = c("#bd0026","#fd8d3c","#fecc5c", "skyblue2")
shape = c(21,23,24,25)
farg2 = "grey59"

#Create median line for forest reference stage
f = metadata %>% filter(Succession == "Forest") 

```



                          ALPHA DIVERSITY PLOTS (Figure 2a-b)
#############################################################################################
```{r Plot alpa diversity fungi}

#Create median horizontal line
h = median(f$shannon_fungi, na.rm = T)

#Fungi
p1 <- metadata %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = shannon_fungi, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(1,6)+
      theme_classic()+
  #geom_line(aes(group = Par),alpha = 0.05)+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
  #theme(legend.position = "none")+
     theme(text=element_text(size=20));p1

```


```{r Plot alpa diversity bacteria}

#Create median horizontal line
h = median(f$shannon_bacteria, na.rm = T)

#Fungi
p2 <- metadata %>%
    bind_rows(tibble(var1 = "trt99")) %>% 
  ggplot(aes(x= Succession, y = shannon_bacteria, fill = Succession))+
  geom_boxplot(aes(fill= Succession),outlier.shape = NA)+
    geom_point(position=position_jitter(0.1, seed = 123),alpha=0.5)+
    scale_fill_manual(values=farg, na.translate = F)+
    scale_color_manual(values=farg, na.translate = F)+
      labs(fill = "Land use", y = "Diversity")+
      ylim(3,7.5)+
      theme_classic()+
  #geom_line(aes(group = Par),alpha = 0.05)+
  scale_x_discrete(limits = c("Managed","Recent","Late","trt99","Forest"),
  breaks = c("Managed","Recent","Late",NA,"Forest"),
  labels = c("Managed","Recent","Late",NA,"Forest"))+
  geom_vline(xintercept = "trt99", linetype = 2, linewidth = 0.2)+
    geom_hline(yintercept = h, linetype = 2, linewidth = 0.9, col = "black")+
  theme(axis.title.x = element_blank())+
  theme(axis.text.x = element_blank())+
    theme(axis.title.y = element_blank())+
  theme(axis.ticks.x = element_blank())+
  #theme(legend.position = "none")+
     theme(text=element_text(size=20));p2


```


```{r Combine plots}

ggarrange(p1,p2,
          common.legend = T,
          legend = "bottom")

ggarrange(p1,p2,
legend = "none")
```



                          BETA DIVERSITY PLOTS (Figure 2c-d)
#############################################################################################

```{r PCoA fungi}

z1 = ps_fungi %>% 
   phyloseq::distance(method = "bray")

k1 <- wcmdscale(d = z1, eig = TRUE)
scores = data.frame(k1$points[,1:2])
scores$Dim1 = scores$Dim1*-1
scores$Succession = factor(ps_fungi@sam_data$Succession)
scores$Succession = ordered(scores$Succession, levels = levels)

p1 = scores %>% 
  ggplot(aes(x = Dim1, y = Dim2,
  color= Succession, shape = Succession, fill = Succession))+
  geom_point(size = 2) +
 scale_color_manual(values=farg)+
  scale_shape_manual(values=shape)+
  theme(legend.key.size = unit(.5, "cm"))+
   stat_ellipse(geom = "polygon",
  aes(fill=Succession), alpha = 0.2, size = 0) +
  scale_fill_manual(values=farg)+
  theme_classic()+
  labs(fill="Land use",color="Land use", shape = "Land use")+
  guides(fill = guide_legend(override.aes = list(alpha = 0.8)))+
  theme(text=element_text(size=17));p1
  
```


```{r PCoA bacteria}

z1 = ps_bacteria %>% 
   phyloseq::distance(method = "bray")

k1 <- wcmdscale(d = z1, eig = TRUE)
scores = data.frame(k1$points[,1:2])
scores$Dim1 = scores$Dim1*-1
scores$Succession = factor(ps_bacteria@sam_data$Succession)
scores$Succession = ordered(scores$Succession, levels = levels)

p2 = scores %>% 
  ggplot(aes(x = Dim1, y = Dim2,
  color= Succession, shape = Succession, fill = Succession))+
  geom_point(size = 2) +
 scale_color_manual(values=farg)+
  scale_shape_manual(values=shape)+
  theme(legend.key.size = unit(.5, "cm"))+
   stat_ellipse(geom = "polygon",
  aes(fill=Succession), alpha = 0.2, size = 0) +
  scale_fill_manual(values=farg)+
  theme_classic()+
  labs(fill="Land use",color="Land use", shape = "Land use")+
  guides(fill = guide_legend(override.aes = list(alpha = 0.8)))+
  theme(text=element_text(size=17));p2

```


```{r Combine plots}

ggarrange(p1,p2,
          common.legend = T,
          legend = "right")


```


                                  EFFECT SIZE PLOT (Figure 2e)
#############################################################################################

```{r}
#plot preparation
es_beta = es_beta %>% 
  filter(Factor == "Succession")

names(es_beta) = c("DF","SoS","F","Omega2_partial","p","Community", "R2", "Comparison",
                   "Diversity","Factor","Covariates")

order = c("Late vs Forest","Recent vs Forest","Managed vs Forest")

es_alpha$Comparison = ordered(es_alpha$Comparison, 
        levels = order)
es_beta$Comparison = ordered(es_beta$Comparison, 
        levels = order)

es_alpha$Community = ordered(es_alpha$Community, 
        levels = c("Fungi","Bacteria"))
es_beta$Community = ordered(es_beta$Community, 
        levels = c("Fungi","Bacteria"))

farg = c("#fecc5c","#fd8d3c", "#bd0026")

```


```{r effect size alpha diversity without covariates}

#Fungi
p1 = es_alpha %>%
   filter(Community == "Fungi") %>%
  filter(Covariates == 0) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_pointrange(aes(ymin = CI_low, ymax = CI_high), 
                  size = 1,linewidth = 1)+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(-0.2,0.4) +
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
 theme(aspect.ratio=3)+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p1


p2 = es_alpha %>%
   filter(Community == "Bacteria") %>%
  filter(Covariates == 0) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_pointrange(aes(ymin = CI_low, ymax = CI_high), 
                  size = 1,linewidth = 1)+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(0,1) +
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
 theme(aspect.ratio=3)+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p2

```


```{r effect size alpha diversity with covariates}

#Fungi
p1 = es_alpha %>%
   filter(Community == "Fungi") %>%
  filter(Covariates == 1) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_pointrange(aes(ymin = CI_low, ymax = CI_high), 
                  size = 1,linewidth = 1)+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(-0.2,0.4) +
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
 theme(aspect.ratio=3)+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p1


p2 = es_alpha %>%
   filter(Community == "Bacteria") %>%
  filter(Covariates == 1) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_pointrange(aes(ymin = CI_low, ymax = CI_high), 
                  size = 1,linewidth = 1)+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(0,1) +
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
 theme(aspect.ratio=3)+
 theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p2

```




```{r effect size beta diversity without covariates}

p1 = es_beta %>%
  filter(Community == "Fungi") %>%
  filter(Covariates == 0) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_point(aes(size=3))+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(0,0.08)+
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
  theme(aspect.ratio=3)+
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p1


p2 = es_beta %>%
    filter(Community == "Bacteria") %>%
  filter(Covariates == 0) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_point(aes(size=3))+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
    ylim(0,0.3)+
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
  theme(aspect.ratio=3)+
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p2


```



```{r effect size beta diversity withcovariates}

p1 = es_beta %>%
  filter(Community == "Fungi") %>%
  filter(Covariates == 1) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_point(aes(size=3))+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
  ylim(-0.01,0.01)+
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
  theme(aspect.ratio=3)+
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p1


p2 = es_beta %>%
    filter(Community == "Bacteria") %>%
  filter(Covariates == 1) %>%
  filter(Diversity == "Taxonomic") %>%
  ggplot(aes(x= Comparison, y = Omega2_partial, color = Comparison))+
  geom_point(aes(size=3))+
  scale_color_manual(values = farg)+
    geom_hline(yintercept = 0, linetype = "dashed") +
  theme_classic()+
    ylim(-0.01,0.01)+
  theme(text=element_text(size=20)) + 
  theme(legend.position = "none")+
    theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(x="", y = "")+
  theme(aspect.ratio=3)+
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip();p2


```











