---
title: "FR_correlation_ver1"
author: "Tord Ranheim"
date: "2024-10-29"
output:
  html_document:
    keep_md: no
---

Correlation between alpha diversity and functional diversity

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi=300,
                      echo=F,
                      cache=T, echo=T)
```



###loading requisite libraries 
```{r libraries to load}
library(tidyverse)
library(rmarkdown)
library(knitr)
library(magrittr)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(ggsci)
library(dplyr)
library(phyloseq)
library(phylosmith)
library(microbiome)
library(vegan)
library(metagMisc)
library(ape)
library(microViz)

```


##Clear the directory and set pathway
```{r}
rm(list=ls())

```


```{r Load metadata file}

metadata = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Processing/Metadata/Result/metadata.txt")
row.names(metadata) = metadata$Sample

```


```{r Load diversity files}

#Load alpha diversity results
ad_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Alpha diversity/Results/alpha_diversity.txt")

#Load nog diversity results
nog_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/NOG/Results/nog_diversity.txt")

#Load cazyme diversity results
cazyme_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Cazyme/Results/cazyme_diversity.txt")

#Load ncyc diversity results
ncyc_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Ncyc/Results/ncyc_diversity.txt")

#Load pcyc diversity results
pcyc_results = read.table("/Users/tranheim/Desktop/Studier/Remiil-NFI/Study 1/Analyses/Functional diversity/Pcyc/Results/pcyc_diversity.txt")

```



                                        PREPARE DATASET
###################################################################################################

```{r merge datasets}

#Merge diversity results
metadata = left_join(metadata,ad_results)
metadata = left_join(metadata,nog_results)
metadata = left_join(metadata,cazyme_results)
metadata = left_join(metadata,ncyc_results)
metadata = left_join(metadata,pcyc_results)

rm(ad_results, nog_results,cazyme_results,ncyc_results,pcyc_results)

```


```{r split dataset}

#Forests
f = metadata %>% filter(Succession == "Forest")
g = metadata %>% filter(Succession != "Forest")

```

 
 
                                            CORRELATIONS
###################################################################################################
Use separate barplots and then merge all plots into one

```{r correlation tests}

#Ad vs nog diversity
cor.test(metadata$shannon_fungi, metadata$nog_diversity_fungi, method = "pearson")
cor.test(metadata$shannon_bacteria, metadata$nog_diversity_bacteria, method = "pearson")

#Ad vs cazyme diversity
cor.test(metadata$shannon_fungi, metadata$cazyme_diversity_fungi, method = "pearson")
cor.test(metadata$shannon_bacteria, metadata$cazyme_diversity_bacteria, method = "pearson")

#Ad vs ncyc diversity
cor.test(metadata$shannon_bacteria, metadata$ncyc_diversity_bacteria, method = "pearson")

#Ad vs pcyc diversity
cor.test(metadata$shannon_fungi, metadata$pcyc_diversity_fungi, method = "pearson")
cor.test(metadata$shannon_bacteria, metadata$pcyc_diversity_bacteria, method = "pearson")

```


```{r correlation tests split by landuse}

#Ad vs nog diversity
cor.test(g$shannon_fungi, g$nog_diversity_fungi, method = "pearson")
cor.test(g$shannon_bacteria, g$nog_diversity_bacteria, method = "pearson")
cor.test(f$shannon_fungi, f$nog_diversity_fungi, method = "pearson")
cor.test(f$shannon_bacteria, f$nog_diversity_bacteria, method = "pearson")


#Ad vs cazyme diversity
cor.test(g$shannon_fungi, g$cazyme_diversity_fungi, method = "pearson")
cor.test(g$shannon_bacteria, g$cazyme_diversity_bacteria, method = "pearson")
cor.test(f$shannon_fungi, f$cazyme_diversity_fungi, method = "pearson")
cor.test(f$shannon_bacteria, f$cazyme_diversity_bacteria, method = "pearson")

#Ad vs ncyc diversity
cor.test(g$shannon_bacteria, g$ncyc_diversity_bacteria, method = "pearson")
cor.test(f$shannon_bacteria, f$ncyc_diversity_bacteria, method = "pearson")

#Ad vs pcyc diversity
cor.test(g$shannon_fungi, g$pcyc_diversity_fungi, method = "pearson")
cor.test(g$shannon_bacteria, g$pcyc_diversity_bacteria, method = "pearson")
cor.test(f$shannon_fungi, f$pcyc_diversity_fungi, method = "pearson")
cor.test(f$shannon_bacteria, f$pcyc_diversity_bacteria, method = "pearson")

```


```{r}


#Test if the correlation coefficients are significantly different by bootstrap tests
r1 = -0.70 #Correlation coefficient for AG 1900s
n1 = 17 #n for AG 1960s
r2 = -0.16 #Correlation coefficient for SNG
n2 = 38 #n for SNG

cocor.indep.groups(
  r1,
  r2,
  n1,
  n2,
  alternative = "two.sided",
  test = "all",
  alpha = 0.05,
  conf.level = 0.95,
  null.value = 0,
  data.name = NULL,
  var.labels = NULL,
  return.htest = FALSE
)

#These bootstrap tests are useless!

```




 
